### ISSUE TITLE
Dark mode preference not applied on app restart

### ISSUE THREAD

**Issue by zahin-mohammad** [power-meter/android-client#28]
- If dark mode preference is set and the app is restarted, the app will display the non-dark UI.

**Comment by zahin-mohammad** [comment]
> * If dark mode preference is set and the app is restarted, the app will display the non-dark UI.

I think we should set the preference for the very first time the app is launched based on the user's system settings. Any preference changes going forward should override the user's system settings.

**Comment by brian-norman** [comment]
I think we shouldn't bother letting them change it, just use system settings, makes it way simpler for us 😁

**Comment by zahin-mohammad** [comment]
> I think we shouldn't bother letting them change it, just use system settings, makes it way simpler for us 😁

It would primarily be for people without A10 since they would not have a system setting in the first place. Since we have this menu setup, might as well make it a feature.

**Comment by zahin-mohammad** [comment]
Fixed in #64
